hostname: Leaf3

bgp:
  asn: 65503
  neighbors:
    - neighbor_as: 65500
      neighbor_ip: 1.1.1.1
    - neighbor_as: 65500
      neighbor_ip: 2.2.2.2
    - neighbor_as: 65500
      neighbor_ip: 3.3.3.3

router_id: 10.0.0.3

v_mac: 02:00:00:00:00:03

interfaces:

  - name: 1/1/1
    mode: layer3
    ipv4_address: 10.0.1.5/31
    mtu: 9216
    description: connection to Spine1
    ospf_enabled: True

  - name: 1/1/2
    mode: layer3
    ipv4_address: 10.0.2.5/31
    mtu: 9216
    description: connection to Spine2
    ospf_enabled: True

  - name: 1/1/3
    mode: layer3
    ipv4_address: 10.0.3.5/31
    mtu: 9216
    description: connection to Spine3
    ospf_enabled: True

loopbacks:

  - name: loopback 1
    mode: layer3
    ipv4_address: 10.0.0.3/32
    description: loopback 1
    ospf_enabled: True

vlans:

  - id: 10
    description: Data_VLAN
    enabled: True
    vrf: VRF1
    ip_address: 192.168.10.4
    ag_ip_mac: "12:00:00:00:01:00"
    ag_ip: 192.168.10.1

  - id: 11
    description: Data_VLAN_SECONDARY
    enabled: True
    vrf: VRF1
    ip_address: 192.168.11.4
    ag_ip_mac: "12:00:00:00:01:00"
    ag_ip: 192.168.11.1

vxlan:
  name: vxlan 1
  source_ip: 10.0.0.3
  vnis:
    - id: 10010
      vlan: 10
    - id: 10011
      vlan: 11
    - id: 100001
      routing: True
      vrf: VRF1

vrfs:

  - name: VRF1
    rd: "65001:1"
    rt_export: "65001:1"
    rt_import: "65001:1"